/** @type {import('next').NextConfig} */
const nextConfig = {
  images: { unoptimized: true },
  trailingSlash: true,
  reactStrictMode: true,
  async redirects() {
    return [
      { source: "/101-foundation", destination: "/sales/101-foundation", permanent: true },
      { source: "/101-foundation/", destination: "/sales/101-foundation/", permanent: true },
      { source: "/201-borrower-conversion", destination: "/sales/201-borrower-conversion", permanent: true },
      { source: "/201-borrower-conversion/", destination: "/sales/201-borrower-conversion/", permanent: true },
      { source: "/301-referral-partner-growth", destination: "/sales/301-referral-partner-growth", permanent: true },
      { source: "/301-referral-partner-growth/", destination: "/sales/301-referral-partner-growth/", permanent: true },
      { source: "/401-content-and-marketing", destination: "/sales/401-content-and-marketing", permanent: true },
      { source: "/401-content-and-marketing/", destination: "/sales/401-content-and-marketing/", permanent: true },
      { source: "/401-content-marketing", destination: "/sales/401-content-and-marketing", permanent: true },
      { source: "/401-content-marketing/", destination: "/sales/401-content-and-marketing/", permanent: true },
      { source: "/501-pipeline-and-sales-systems", destination: "/sales/501-pipeline-and-sales-systems", permanent: true },
      { source: "/501-pipeline-and-sales-systems/", destination: "/sales/501-pipeline-and-sales-systems/", permanent: true },
      { source: "/501-pipeline-sales-systems", destination: "/sales/501-pipeline-and-sales-systems", permanent: true },
      { source: "/501-pipeline-sales-systems/", destination: "/sales/501-pipeline-and-sales-systems/", permanent: true },
      { source: "/601-elite-execution", destination: "/sales/601-elite-execution", permanent: true },
      { source: "/601-elite-execution/", destination: "/sales/601-elite-execution/", permanent: true },
      { source: "/personality-quiz", destination: "/onboarding/personality", permanent: true },
      { source: "/personality-quiz/", destination: "/onboarding/personality/", permanent: true },
      { source: "/new-lo-aptitude-quiz", destination: "/onboarding/aptitude", permanent: true },
      { source: "/new-lo-aptitude-quiz/", destination: "/onboarding/aptitude/", permanent: true },
      { source: "/quiz-results", destination: "/onboarding/results", permanent: true },
      { source: "/quiz-results/", destination: "/onboarding/results/", permanent: true },
      { source: "/prompts", destination: "/resources/?tab=prompts", permanent: true },
      { source: "/prompts/", destination: "/resources/?tab=prompts", permanent: true },
      { source: "/scripts", destination: "/resources/?tab=scripts", permanent: true },
      { source: "/scripts/", destination: "/resources/?tab=scripts", permanent: true },
      { source: "/roleplays", destination: "/resources/?tab=roleplays", permanent: true },
      { source: "/roleplays/", destination: "/resources/?tab=roleplays", permanent: true },
      { source: "/audio-training", destination: "/replays/?tab=audio", permanent: true },
      { source: "/audio-training/", destination: "/replays/?tab=audio", permanent: true },
      { source: "/recordings", destination: "/replays/?tab=recordings", permanent: true },
      { source: "/recordings/", destination: "/replays/?tab=recordings", permanent: true },
      { source: "/recommended-channels", destination: "/resources/?tab=channels", permanent: true },
      { source: "/recommended-channels/", destination: "/resources/?tab=channels", permanent: true },
    ];
  },
};

export default nextConfig;
